const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST'
const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE'

export {
  FETCH_PROJECTS_REQUEST,
  FETCH_PROJECTS_SUCCESS,
  FETCH_PROJECTS_FAILURE,
}
