const FETCH_ROLES_REQUEST = 'FETCH_ROLES_REQUEST'
const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS'
const FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE'

export {
  FETCH_ROLES_REQUEST,
  FETCH_ROLES_SUCCESS,
  FETCH_ROLES_FAILURE,
}
