const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

const UPDATE_USER_SUCCESS = 'UPDATE_USERS_SUCCESS'
const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
const RESET_SUCCESS_MESSAGE = 'RESET_SUCCESS_MESSAGE'

export {
  FETCH_USERS_REQUEST,
  FETCH_USERS_SUCCESS,
  FETCH_USERS_FAILURE,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAILURE,
  RESET_SUCCESS_MESSAGE,
}
